In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import Perceptron
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    fbeta_score,
    precision_recall_curve,
    precision_score,
    PrecisionRecallDisplay,
    recall_score,
    roc_auc_score,
    roc_curve,
    RocCurveDisplay,
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from src.config import DADOS_LIMPOS
from src.models import RANDOM_STATE

In [2]:
df = pd.read_parquet(DADOS_LIMPOS)

df.head()

,area_mean,area_se,area_worst,compactness_mean,compactness_se,compactness_worst,concave points_mean,concave points_se,concave points_worst,concavity_mean,...,radius_worst,smoothness_mean,smoothness_se,smoothness_worst,symmetry_mean,symmetry_se,symmetry_worst,texture_mean,texture_se,texture_worst
0,1001.0,153.40,2019.0,0.27760,0.04904,0.6656,0.14710,0.01587,0.2654,0.3001,...,25.38,0.11840,0.006399,0.1622,0.2419,0.03003,0.4601,10.38,0.9053,17.33
1,1326.0,74.08,1956.0,0.07864,0.01308,0.1866,0.07017,0.01340,0.1860,0.0869,...,24.99,0.08474,0.005225,0.1238,0.1812,0.01389,0.2750,17.77,0.7339,23.41
2,1203.0,94.03,1709.0,0.15990,0.04006,0.4245,0.12790,0.02058,0.2430,0.1974,...,23.57,0.10960,0.006150,0.1444,0.2069,0.02250,0.3613,21.25,0.7869,25.53
3,386.1,27.23,567.7,0.28390,0.07458,0.8663,0.10520,0.01867,0.2575,0.2414,...,14.91,0.14250,0.009110,0.2098,0.2597,0.05963,0.6638,20.38,1.1560,26.50
4,1297.0,94.44,1575.0,0.13280,0.02461,0.2050,0.10430,0.01885,0.1625,0.1980,...,22.54,0.10030,0.011490,0.1374,0.1809,0.01756,0.2364,14.34,0.7813,16.67


In [3]:
X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]

In [4]:
y.head()

0    M
1    M
2    M
3    M
4    M
Name: diagnosis, dtype: str

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

In [5]:
le = LabelEncoder()

y = le.fit_transform(y)

y[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
le.classes_

array(['B', 'M'], dtype=object)

In [7]:
y[:20]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=RANDOM_STATE, stratify=y
)

https://numpy.org/doc/stable/reference/generated/numpy.bincount.html

In [9]:
np.bincount(y_train)

array([267, 159])

In [10]:
np.bincount(y_train) / len(y_train)

array([0.62676056, 0.37323944])

In [11]:
np.bincount(y_test)

array([90, 53])

In [12]:
np.bincount(y_test) / len(y_test)

array([0.62937063, 0.37062937])

In [13]:
clf = Perceptron()

clf.fit(X_train, y_train)

,"penalty penalty: {'l2','l1','elasticnet'}, default=NoneThe penalty (aka regularization term) to be used.",None
,"alpha alpha: float, default=0.0001Constant that multiplies the regularization term if regularization isused.",0.0001
,"l1_ratio l1_ratio: float, default=0.15The Elastic Net mixing parameter, with `0 <= l1_ratio <= 1`.`l1_ratio=0` corresponds to L2 penalty, `l1_ratio=1` to L1.Only used if `penalty='elasticnet'`... versionadded:: 0.24",0.15
,"fit_intercept fit_intercept: bool, default=TrueWhether the intercept should be estimated or not. If False, thedata is assumed to be already centered.",True
,"max_iter max_iter: int, default=1000The maximum number of passes over the training data (aka epochs).It only impacts the behavior in the ``fit`` method, and not the:meth:`partial_fit` method... versionadded:: 0.19",1000
,"tol tol: float or None, default=1e-3The stopping criterion. If it is not None, the iterations will stopwhen (loss > previous_loss - tol)... versionadded:: 0.19",0.001
,"shuffle shuffle: bool, default=TrueWhether or not the training data should be shuffled after each epoch.",True
,"verbose verbose: int, default=0The verbosity level.",0
,"eta0 eta0: float, default=1Constant by which the updates are multiplied.",1.0
,"n_jobs n_jobs: int, default=NoneThe number of CPUs to use to do the OVA (One Versus All, formulti-class problems) computation.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.",None
,"random_state random_state: int, RandomState instance or None, default=0Used to shuffle the training data, when ``shuffle`` is set to``True``. Pass an int for reproducible output across multiplefunction calls.See :term:`Glossary `.",0


In [14]:
y_pred = clf.predict(X_test)

In [15]:
clf.score(X_test, y_test)

0.9020979020979021

O `score` do classificador retorna a acurácia do modelo, que é a proporção de predições corretas feitas pelo modelo. Podemos calcular a acurácia comparando as predições feitas pelo modelo com as respostas corretas. A acurácia é dada por:

$$
\text{acurácia} = \frac{\text{número de predições corretas}}{\text{número total de predições}} 
$$

Uma acurácia de 1.0 significa que o modelo fez todas as predições corretas, enquanto uma acurácia de 0.0 significa que o modelo fez todas as predições erradas.

In [16]:
print(y_test[:20])
print(y_pred[:20])

[1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1]
[1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0]


No nosso caso, temos uma acurácia de aproximadamente 0.902, ou seja, 90.2% das predições feitas na base de teste foram corretas.

https://scikit-learn.org/stable/modules/model_evaluation.html

In [17]:
accuracy_score(y_test, y_pred)

0.9020979020979021

No entanto, a acurácia não é uma métrica perfeita para avaliar a qualidade de um modelo. Por exemplo, se tivermos um dataset com 90% de exemplos da classe 1 e 10% de exemplos da classe 0, um modelo que sempre prediz a classe 1 terá uma acurácia de 90%, mas não é um modelo útil.

In [18]:
print(np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0]))  # dataset

print(np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))  # resultado do modelo

[1 1 1 1 1 1 1 1 1 0]
[1 1 1 1 1 1 1 1 1 1]


Além disso, a acurácia trata todos os erros da mesma forma, mas em muitos casos, erros de um tipo podem ser mais graves que erros de outro tipo. Por exemplo, em um problema de detecção de doenças, um falso negativo (dizer que um paciente não tem a doença quando ele tem) pode ser mais grave que um falso positivo (dizer que um paciente tem a doença quando ele não tem).